import type { SystemDesign } from "@agentdock/config-schema";

export function generateReadme(design: SystemDesign): string {
  const agentRows = design.agents
    .map((a) => `| \`${a.id}\` | ${a.name} | ${a.llm.provider}/${a.llm.model} | ${a.expose.join(", ")} |`)
    .join("\n");

  const connRows = design.connections.length > 0
    ? design.connections.map((c) => `| \`${c.from}\` → \`${c.to}\` | ${c.trigger.type} |`).join("\n")
    : "| — | No connections defined |";

  return `# ${design.systemName}

Generated by [AgentDock Builder](https://github.com/your-org/agentdock).

## Quick Start

\`\`\`bash
cp .env.example .env
# Edit .env — fill in JWT_SECRET and any LLM API keys
docker compose up --build
\`\`\`

Orchestrator API: \`http://localhost:4000\`

## Agents

| ID | Name | LLM | Exposed Endpoints |
|---|---|---|---|
${agentRows}

## Connections

| Route | Trigger |
|---|---|
${connRows}

## API

\`\`\`bash
# Health check
GET http://localhost:4000/health

# Agent status (requires expose: status)
GET http://localhost:4000/api/agents/{agent-id}/status
Authorization: Bearer {jwt}

# Agent logs (requires expose: logs)
GET http://localhost:4000/api/agents/{agent-id}/logs
Authorization: Bearer {jwt}

# Chat with agent (requires expose: chat)
POST http://localhost:4000/api/agents/{agent-id}/chat
Authorization: Bearer {jwt}
Content-Type: application/json
{"message": "Hello"}

# Hot-reload agent config
POST http://localhost:4000/api/agents/{agent-id}/reload
Authorization: Bearer {jwt}

# WebSocket events
WS ws://localhost:4000/ws?token={jwt}
\`\`\`

## Hot-Editing

To change an agent's config without full regeneration:
1. Edit \`configs/agents/{agent-id}.yaml\`
2. \`curl -X POST http://localhost:4000/api/agents/{agent-id}/reload -H "Authorization: Bearer {jwt}"\`
3. Only that agent restarts — rest of system unaffected.

## System ID

\`${design.systemId}\`
`;
}
