import type { SystemDesign } from "@agentdock/config-schema";

export function generateReadme(design: SystemDesign): string {
  const port = 4000;
  const base = `http://localhost:${port}`;

  // Per-agent endpoint sections — only show endpoints that are actually exposed
  const agentSections = design.agents.map((a) => {
    const exposed = new Set(a.expose);
    const lines: string[] = [`### ${a.name} (\`${a.id}\`)`];
    lines.push(`- **Model:** ${a.llm.provider}/${a.llm.model}`);
    lines.push(`- **Exposed:** ${a.expose.length > 0 ? a.expose.join(", ") : "none"}`);
    lines.push("");

    if (exposed.has("status")) {
      lines.push(`\`\`\`bash`);
      lines.push(`curl ${base}/api/agents/${a.id}/status \\`);
      lines.push(`  -H "Authorization: Bearer $TOKEN"`);
      lines.push(`\`\`\``);
    }
    if (exposed.has("logs")) {
      lines.push(`\`\`\`bash`);
      lines.push(`curl "${base}/api/agents/${a.id}/logs?limit=50" \\`);
      lines.push(`  -H "Authorization: Bearer $TOKEN"`);
      lines.push(`\`\`\``);
    }
    if (exposed.has("memory")) {
      lines.push(`\`\`\`bash`);
      lines.push(`# List memory files`);
      lines.push(`curl ${base}/api/agents/${a.id}/memory \\`);
      lines.push(`  -H "Authorization: Bearer $TOKEN"`);
      lines.push(``);
      lines.push(`# Read a specific file`);
      lines.push(`curl ${base}/api/agents/${a.id}/memory/report.md \\`);
      lines.push(`  -H "Authorization: Bearer $TOKEN"`);
      lines.push(`\`\`\``);
    }
    if (exposed.has("tasks")) {
      lines.push(`\`\`\`bash`);
      lines.push(`curl ${base}/api/agents/${a.id}/tasks \\`);
      lines.push(`  -H "Authorization: Bearer $TOKEN"`);
      lines.push(`\`\`\``);
    }
    if (exposed.has("chat")) {
      lines.push(`\`\`\`bash`);
      lines.push(`curl -X POST ${base}/api/agents/${a.id}/chat \\`);
      lines.push(`  -H "Authorization: Bearer $TOKEN" \\`);
      lines.push(`  -H "Content-Type: application/json" \\`);
      lines.push(`  -d '{"message": "What have you found so far?"}'`);
      lines.push(`\`\`\``);
    }
    if (exposed.has("rag")) {
      lines.push(`\`\`\`bash`);
      lines.push(`# RAG status`);
      lines.push(`curl ${base}/api/agents/${a.id}/rag/status \\`);
      lines.push(`  -H "Authorization: Bearer $TOKEN"`);
      lines.push(``);
      lines.push(`# Force re-index`);
      lines.push(`curl -X POST ${base}/api/agents/${a.id}/rag/reindex \\`);
      lines.push(`  -H "Authorization: Bearer $TOKEN"`);
      lines.push(`\`\`\``);
    }

    // Webhook trigger if agent has webhook trigger
    const hasWebhook = a.triggers?.some((t: { type: string }) => t.type === "webhook");
    if (hasWebhook) {
      lines.push(`\`\`\`bash`);
      lines.push(`# Trigger via webhook (no token required)`);
      lines.push(`curl -X POST ${base}/webhooks/${a.id} \\`);
      lines.push(`  -H "Content-Type: application/json" \\`);
      lines.push(`  -d '{"instruction": "Start your task"}'`);
      lines.push(`\`\`\``);
    }

    return lines.join("\n");
  }).join("\n\n---\n\n");

  const agentTableRows = design.agents
    .map((a) => `| \`${a.id}\` | ${a.name} | ${a.llm.provider}/${a.llm.model} | ${a.expose.join(", ") || "none"} |`)
    .join("\n");

  const connRows = design.connections.length > 0
    ? design.connections.map((c) => `| \`${c.from}\` → \`${c.to}\` | ${c.trigger.type} |`).join("\n")
    : "| — | No connections defined |";

  return `# ${design.systemName}

Generated by [AgentDock Builder](https://github.com/your-org/agentdock).

## Quick Start

\`\`\`bash
cp .env.example .env
# Edit .env:
#   JWT_SECRET=<random 32+ char string>
#   API_PASSWORD=<your chosen password>   # used to log in and get a token
#   OLLAMA_SERVERS=http://host.docker.internal:11434  # if using Ollama
docker compose up --build
\`\`\`

Orchestrator API: \`${base}\`

---

## Authentication

This system uses JWT. There is no user registration — access is controlled by a single password set in your \`.env\` file.

**Set your password in \`.env\`:**
\`\`\`env
API_PASSWORD=your-chosen-password   # if not set, defaults to JWT_SECRET
\`\`\`

**Get a token:**
\`\`\`bash
curl -X POST ${base}/auth/login \\
  -H "Content-Type: application/json" \\
  -d '{"password": "your-chosen-password"}'
\`\`\`

Response:
\`\`\`json
{ "token": "eyJhbGciOiJIUzI1NiJ9...", "expiresIn": "24h" }
\`\`\`

**Save the token for subsequent requests:**
\`\`\`bash
TOKEN=$(curl -s -X POST ${base}/auth/login \\
  -H "Content-Type: application/json" \\
  -d '{"password": "your-chosen-password"}' | jq -r .token)
\`\`\`

All \`/api/*\` endpoints require \`Authorization: Bearer $TOKEN\`. Webhooks are public (no token needed).

---

## Agents

| ID | Name | LLM | Exposed Endpoints |
|---|---|---|---|
${agentTableRows}

## Pipeline

| Route | Trigger |
|---|---|
${connRows}

---

## Testing the System

### 1. Health check (no token needed)
\`\`\`bash
curl ${base}/health
\`\`\`

### 2. Get a token
\`\`\`bash
TOKEN=$(curl -s -X POST ${base}/auth/login \\
  -H "Content-Type: application/json" \\
  -d '{"password": "your-chosen-password"}' | jq -r .token)
echo $TOKEN
\`\`\`

### 3. System status
\`\`\`bash
curl ${base}/api/system/status -H "Authorization: Bearer $TOKEN"
\`\`\`

### 4. Trigger the pipeline via webhook
\`\`\`bash
curl -X POST ${base}/webhooks/${design.agents[0]?.id ?? "agent-id"} \\
  -H "Content-Type: application/json" \\
  -d '{"instruction": "Run your task"}'
\`\`\`

### 5. Watch real-time events (WebSocket)
\`\`\`bash
# Using websocat (install: cargo install websocat)
websocat "ws://localhost:${port}/ws?token=$TOKEN"
\`\`\`

---

## Agent Endpoints

> Endpoints not in an agent's \`expose\` list return \`403 Forbidden\`.

${agentSections}

---

## Hot-Editing

Change an agent's config without full regeneration:
\`\`\`bash
# 1. Edit the config
vim configs/agents/<agent-id>.yaml

# 2. Reload only that agent (rest of system unaffected)
curl -X POST ${base}/api/agents/<agent-id>/reload \\
  -H "Authorization: Bearer $TOKEN"
\`\`\`

---

## System ID

\`${design.systemId}\`
`;
}
